# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  SETUP_MAGE_VERSION: '1.15.0'
  SETUP_GVM_VERSION: 'v0.5.0'

steps:
  - label: ":buildkite: Lint"
    command:
      - ".buildkite/scripts/lint.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"

  - label: ":linux: Test Linux"
    key: test-lin
    command:
      - ".buildkite/scripts/test.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "12G"

  - label: ":windows: Test Windows"
    key: test-win
    command:
      - ".buildkite/scripts/test.ps1"
    agents:
      provider: "gcp"
      image: "family/core-windows-2019"
      cpu: "8"
      memory: "12G"
